# Generated by Django 3.2.23 on 2024-02-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='upated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
